### PR TITLE
Haslineage migration endpoint to set correct __hasLineage value

### PR DESCRIPTION
**Pull request by nixon-atlan**
## Change description
Haslineage migration endpoint to set correct __hasLineage value
> Description here

API call - method = POST

http://atlas_host:21000/api/atlas/v2/entity/repairhaslineage

```
{
    "request": [
        {
            "processGuid": "b4abb838-b2e2-431e-a876-015209b1d05b",
            "endGuid": "9a71deec-1148-4108-b0f7-533aa04b6527",
            "label": "__Process.outputs"
        },
        {
            "processGuid": "79bd0cb1-261b-4b87-aa32-e9050ffcc719",
            "endGuid": "fa20d311-d80e-4c68-a77f-a1dba4e00a5e",
            "label": "__Process.inputs"
        }
    ]
}
```

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by mehtaanshul** [comment]
Why aren't we checking edge status? Shouldn't we check if edge is Active or not?

**Comment by mehtaanshul** [comment]
Why aren't we checking edge status? Shouldn't we check if edge is Active or not?

**Comment by nixon-atlan** [comment]
> Why aren't we checking edge status? Shouldn't we check if edge is Active or not?
Make sense, will skip input/output edges which are not ACTIVE in status.

**Comment by nixon-atlan** [comment]
> What will happen if addHasLineage is called via some other workflow for entities which have incorrect value of __hasLineage at the same time when repairHasLineage workflow is running?
@mehtaanshul 
Both the method the _addHasLineage_ and _repairHasLineage_ will be part of different transaction, if both the methods are dealing with same edge concurrently then it will be handles at janusgraph level.

**Review by mehtaanshul — APPROVED** [review]

**Review by mehtaanshul — CHANGES_REQUESTED** [review]
Will check this out in some time

**Review by mehtaanshul — APPROVED** [review]

**Pull request merged**
