### PR TITLE
 META-3050 Get Accessors API: return deny users/groups/roles

### PR DESCRIPTION
**Pull request by nikhilbonte21**

### CODE REVIEW

**Review by mehtaanshul — APPROVED** [review]

**Review by mehtaanshul — COMMENTED** [review]
.

**Review by mehtaanshul — CHANGES_REQUESTED** [review]
Do not merge until ranger pr is approved and changes are updating in this one

**Review by mehtaanshul — DISMISSED** [review]

**Review by nixon-atlan — APPROVED** [review]
+1

**Review by nixon-atlan — APPROVED** [review]
+1

**Pull request merged**
